//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailMe.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Groupid { get; set; }
        public string GroupName { get; set; }
        public string Group_enable { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
