//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailMe.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs_Using
    {
        public System.Guid LogID { get; set; }
        public string LogStatus { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.Guid> By { get; set; }
        public Nullable<System.Guid> What { get; set; }
    
        public virtual User User { get; set; }
    }
}
