//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailMe.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Events = new HashSet<Event>();
        }
    
        public System.Guid TrackID { get; set; }
        public string TrackName { get; set; }
        public string LocationZone { get; set; }
        public Nullable<int> DistanceKM { get; set; }
        public string LevelOfDifficulty { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Track_enable { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
