//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailMe.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Logs_Using = new HashSet<Logs_Using>();
            this.Groups = new HashSet<Group>();
        }
    
        public System.Guid UserID { get; set; }
        public string MailAddress { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string user_enable { get; set; }
    
        public virtual ICollection<Logs_Using> Logs_Using { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
