//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailMe.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Languages = new HashSet<Language>();
            this.Skills = new HashSet<Skill>();
            this.Groups = new HashSet<Group>();
            this.Tracks = new HashSet<Track>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string MailAddress { get; set; }
        public System.DateTime Birthdate { get; set; }
    
        public virtual ICollection<Language> Languages { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
